/* tslint:disable */
/* eslint-disable */
/**
 * PYRED
 * Internal APIs
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActionInfo
 */
export interface ActionInfo {
    /**
     * 
     * @type {string}
     * @memberof ActionInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ActionInfo
     */
    description: string;
}

export function ActionInfoFromJSON(json: any): ActionInfo {
    return ActionInfoFromJSONTyped(json, false);
}

export function ActionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function ActionInfoToJSON(value?: ActionInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}


