/* tslint:disable */
/* eslint-disable */
/**
 * BINP
 * Internal APIs
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Journal header
 * @export
 * @interface Headline
 */
export interface Headline {
    /**
     * 
     * @type {number}
     * @memberof Headline
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Headline
     */
    operation: string;
    /**
     * 
     * @type {string}
     * @memberof Headline
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof Headline
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Headline
     */
    finishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Headline
     */
    error?: string;
    /**
     * 
     * @type {number}
     * @memberof Headline
     */
    duration?: number;
}

export function HeadlineFromJSON(json: any): Headline {
    return HeadlineFromJSONTyped(json, false);
}

export function HeadlineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Headline {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'operation': json['operation'],
        'description': json['description'],
        'startedAt': (new Date(json['started_at'])),
        'finishedAt': !exists(json, 'finished_at') ? undefined : (new Date(json['finished_at'])),
        'error': !exists(json, 'error') ? undefined : json['error'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
    };
}

export function HeadlineToJSON(value?: Headline | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'operation': value.operation,
        'description': value.description,
        'started_at': (value.startedAt.toISOString()),
        'finished_at': value.finishedAt === undefined ? undefined : (value.finishedAt.toISOString()),
        'error': value.error,
        'duration': value.duration,
    };
}


