/* tslint:disable */
/* eslint-disable */
/**
 * BINP
 * Internal APIs
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Status,
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
} from './';

/**
 * Service information
 * @export
 * @interface Info
 */
export interface Info {
    /**
     * 
     * @type {string}
     * @memberof Info
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Info
     */
    description: string;
    /**
     * 
     * @type {Status}
     * @memberof Info
     */
    status: Status;
    /**
     * 
     * @type {boolean}
     * @memberof Info
     */
    autostart: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Info
     */
    restart: boolean;
    /**
     * 
     * @type {number}
     * @memberof Info
     */
    restartDelay: number;
}

export function InfoFromJSON(json: any): Info {
    return InfoFromJSONTyped(json, false);
}

export function InfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Info {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'status': StatusFromJSON(json['status']),
        'autostart': json['autostart'],
        'restart': json['restart'],
        'restartDelay': json['restart_delay'],
    };
}

export function InfoToJSON(value?: Info | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'status': StatusToJSON(value.status),
        'autostart': value.autostart,
        'restart': value.restart,
        'restart_delay': value.restartDelay,
    };
}


