/* tslint:disable */
/* eslint-disable */
/**
 * BINP
 * Internal APIs
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceControl
 */
export interface ServiceControl {
    /**
     * 
     * @type {boolean}
     * @memberof ServiceControl
     */
    running: boolean;
}

export function ServiceControlFromJSON(json: any): ServiceControl {
    return ServiceControlFromJSONTyped(json, false);
}

export function ServiceControlFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceControl {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'running': json['running'],
    };
}

export function ServiceControlToJSON(value?: ServiceControl | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'running': value.running,
    };
}


