<div class="flex w-100 text-center">
    <div class="loadingio-spinner-spin-lp2qbbq9rv">
        <div class="ldio-rymymjla7j">
            <div>
                <div></div>
            </div>
            <div>
                <div></div>
            </div>
            <div>
                <div></div>
            </div>
            <div>
                <div></div>
            </div>
            <div>
                <div></div>
            </div>
            <div>
                <div></div>
            </div>
            <div>
                <div></div>
            </div>
            <div>
                <div></div>
            </div>
        </div>
    </div>
</div>

<style type="text/css">
    @keyframes ldio-rymymjla7j {
        0% {
            opacity: 1;
            backface-visibility: hidden;
            transform: translateZ(0) scale(1.5, 1.5);
        }
        100% {
            opacity: 0;
            backface-visibility: hidden;
            transform: translateZ(0) scale(1, 1);
        }
    }

    .ldio-rymymjla7j div > div {
        position: absolute;
        width: 14px;
        height: 14px;
        border-radius: 50%;
        background: #1d0e0b;
        animation: ldio-rymymjla7j 1s linear infinite;
    }

    .ldio-rymymjla7j div:nth-child(1) > div {
        left: 75px;
        top: 43px;
        animation-delay: -0.875s;
    }

    .ldio-rymymjla7j > div:nth-child(1) {
        transform: rotate(0deg);
        transform-origin: 82px 50px;
    }

    .ldio-rymymjla7j div:nth-child(2) > div {
        left: 66px;
        top: 66px;
        animation-delay: -0.75s;
    }

    .ldio-rymymjla7j > div:nth-child(2) {
        transform: rotate(45deg);
        transform-origin: 73px 73px;
    }

    .ldio-rymymjla7j div:nth-child(3) > div {
        left: 43px;
        top: 75px;
        animation-delay: -0.625s;
    }

    .ldio-rymymjla7j > div:nth-child(3) {
        transform: rotate(90deg);
        transform-origin: 50px 82px;
    }

    .ldio-rymymjla7j div:nth-child(4) > div {
        left: 20px;
        top: 66px;
        animation-delay: -0.5s;
    }

    .ldio-rymymjla7j > div:nth-child(4) {
        transform: rotate(135deg);
        transform-origin: 27px 73px;
    }

    .ldio-rymymjla7j div:nth-child(5) > div {
        left: 11px;
        top: 43px;
        animation-delay: -0.375s;
    }

    .ldio-rymymjla7j > div:nth-child(5) {
        transform: rotate(180deg);
        transform-origin: 18px 50px;
    }

    .ldio-rymymjla7j div:nth-child(6) > div {
        left: 20px;
        top: 20px;
        animation-delay: -0.25s;
    }

    .ldio-rymymjla7j > div:nth-child(6) {
        transform: rotate(225deg);
        transform-origin: 27px 27px;
    }

    .ldio-rymymjla7j div:nth-child(7) > div {
        left: 43px;
        top: 11px;
        animation-delay: -0.125s;
    }

    .ldio-rymymjla7j > div:nth-child(7) {
        transform: rotate(270deg);
        transform-origin: 50px 18px;
    }

    .ldio-rymymjla7j div:nth-child(8) > div {
        left: 66px;
        top: 20px;
        animation-delay: 0s;
    }

    .ldio-rymymjla7j > div:nth-child(8) {
        transform: rotate(315deg);
        transform-origin: 73px 27px;
    }

    .loadingio-spinner-spin-lp2qbbq9rv {
        width: 32px;
        height: 32px;
        display: inline-block;
        overflow: hidden;
        background: rgba(NaN, NaN, NaN, 0);
    }

    .ldio-rymymjla7j {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(0.32);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }

    .ldio-rymymjla7j div {
        box-sizing: content-box;
    }

    /* generated by https://loading.io/ */
</style>