/* tslint:disable */
/* eslint-disable */
/**
 * BINP
 * Internal APIs
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ActionInfo,
    ActionInfoFromJSON,
    ActionInfoToJSON,
    HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    Headline,
    HeadlineFromJSON,
    HeadlineToJSON,
    Info,
    InfoFromJSON,
    InfoToJSON,
    InvokeResult,
    InvokeResultFromJSON,
    InvokeResultToJSON,
    Journal,
    JournalFromJSON,
    JournalToJSON,
    Query,
    QueryFromJSON,
    QueryToJSON,
    ServiceControl,
    ServiceControlFromJSON,
    ServiceControlToJSON,
} from '../models';

export interface GetJournalRequest {
    journalId: number;
}

export interface InvokeActionRequest {
    name: string;
}

export interface ListJournalsRequest {
    page?: number;
}

export interface ManageServiceRequest {
    name: string;
    serviceControl: ServiceControl;
}

export interface SearchJournalsRequest {
    query: Query;
    page?: number;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get single journal record by ID. If no record found - 404 returned.
     * Get Journal
     */
    async getJournalRaw(requestParameters: GetJournalRequest): Promise<runtime.ApiResponse<Journal>> {
        if (requestParameters.journalId === null || requestParameters.journalId === undefined) {
            throw new runtime.RequiredError('journalId','Required parameter requestParameters.journalId was null or undefined when calling getJournal.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/journal/{journal_id}`.replace(`{${"journal_id"}}`, encodeURIComponent(String(requestParameters.journalId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => JournalFromJSON(jsonValue));
    }

    /**
     * Get single journal record by ID. If no record found - 404 returned.
     * Get Journal
     */
    async getJournal(requestParameters: GetJournalRequest): Promise<Journal> {
        const response = await this.getJournalRaw(requestParameters);
        return await response.value();
    }

    /**
     * Invoke custom action (methods annotated by @action)
     * Invoke Action
     */
    async invokeActionRaw(requestParameters: InvokeActionRequest): Promise<runtime.ApiResponse<InvokeResult>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling invokeAction.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/action/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InvokeResultFromJSON(jsonValue));
    }

    /**
     * Invoke custom action (methods annotated by @action)
     * Invoke Action
     */
    async invokeAction(requestParameters: InvokeActionRequest): Promise<InvokeResult> {
        const response = await this.invokeActionRaw(requestParameters);
        return await response.value();
    }

    /**
     * List available actions
     * List Actions
     */
    async listActionsRaw(): Promise<runtime.ApiResponse<Array<ActionInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/actions/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ActionInfoFromJSON));
    }

    /**
     * List available actions
     * List Actions
     */
    async listActions(): Promise<Array<ActionInfo>> {
        const response = await this.listActionsRaw();
        return await response.value();
    }

    /**
     * List journal records in reverse order
     * List Journals
     */
    async listJournalsRaw(requestParameters: ListJournalsRequest): Promise<runtime.ApiResponse<Array<Headline>>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/journals/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HeadlineFromJSON));
    }

    /**
     * List journal records in reverse order
     * List Journals
     */
    async listJournals(requestParameters: ListJournalsRequest): Promise<Array<Headline>> {
        const response = await this.listJournalsRaw(requestParameters);
        return await response.value();
    }

    /**
     * List all defined services
     * List Services
     */
    async listServicesRaw(): Promise<runtime.ApiResponse<Array<Info>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/services/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InfoFromJSON));
    }

    /**
     * List all defined services
     * List Services
     */
    async listServices(): Promise<Array<Info>> {
        const response = await this.listServicesRaw();
        return await response.value();
    }

    /**
     * Manage Service
     */
    async manageServiceRaw(requestParameters: ManageServiceRequest): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling manageService.');
        }

        if (requestParameters.serviceControl === null || requestParameters.serviceControl === undefined) {
            throw new runtime.RequiredError('serviceControl','Required parameter requestParameters.serviceControl was null or undefined when calling manageService.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/service/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceControlToJSON(requestParameters.serviceControl),
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Manage Service
     */
    async manageService(requestParameters: ManageServiceRequest): Promise<any> {
        const response = await this.manageServiceRaw(requestParameters);
        return await response.value();
    }

    /**
     * Search journals
     * Search Journals
     */
    async searchJournalsRaw(requestParameters: SearchJournalsRequest): Promise<runtime.ApiResponse<Array<Headline>>> {
        if (requestParameters.query === null || requestParameters.query === undefined) {
            throw new runtime.RequiredError('query','Required parameter requestParameters.query was null or undefined when calling searchJournals.');
        }

        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/journals/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryToJSON(requestParameters.query),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HeadlineFromJSON));
    }

    /**
     * Search journals
     * Search Journals
     */
    async searchJournals(requestParameters: SearchJournalsRequest): Promise<Array<Headline>> {
        const response = await this.searchJournalsRaw(requestParameters);
        return await response.value();
    }

}
