name: Build and release
on:
  push:
    tags:
      - 'v*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Setup dev packages
      run: pip3 install -r requirements.dev.txt
    - name: Setup UI packages
      run: |
        cd ui
        npm install .
    - name: Build and release to PyPi
      run: |
        make release-github
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_BINP_TOKEN }}
