name: Build and release
on:
  push:
    tags:
      - 'v*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Setup dev packages
      run: pip3 install -r requirements.dev.txt

    - name: Run PyPi release
      run: |
        make release-github
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_BINP_TOKEN }}
